# An unique identifier for the head node and workers of this cluster.
cluster_name: minimal

# The maximum number of workers nodes to launch in addition to the head
# node. min_workers default to 0.
max_workers: 2

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a

available_node_types:
   default:
      resources: {}
      node_config:
         InstanceType: t2.medium

head_node_type: default

auth:
    ssh_user: ubuntu
